### Dataset ###
data:
  name: synthetic_pretrain
  folder: datasets/motor/pretrain


### Train ###
train:
  epochs: 500
  batch_size: 512
  lr: 1.0e-3
  model_path: ""
  output_folder: pretrain
  val_epoch_interval: 1
  display_interval: 1
