### Dataset ###
data:
  name: synthetic
  folder: ./datasets/air/city


### Evaluate ###
eval:
  n_samples: 10
  model_path: ""
  batch_size: 128
  display_interval: 1
  output_folder: eval

  device: cuda:0
  attr_list: [city, season]
  ctap_folder: save/air/energy/0
