device: cuda:0

diffusion:
  type: CSDI
  layers: 3
  channels: 64
  nheads: 8
  diffusion_embedding_dim: 128
  is_linear: False  # linear transformer

  beta_start: 0.0001
  beta_end: 0.5
  schedule: "quad"

  num_steps: 50

  # edit
  edit_steps: 50  # the number of steps to perform editing
  bootstrap_ratio: 0.5   # [0,1]

  #
  is_attr_proj: True

side:
  num_var: 1
  var_emb: 16
  time_emb: 128
  
attrs:
  attr_emb: 64