### Dataset ###
data:
  name: synthetic_pretrain
  folder: datasets/air/pretrain


### Train ###
train:
  epochs: 200
  batch_size: 256
  lr: 1.0e-5
  itr_per_epoch: 1.0e+8
  model_path: ""
  output_folder: pretrain
  val_epoch_interval: 1
  display_interval: 1
